name: phpunit

on:
  push:
    branches:
      - 1.x
  pull_request:
    branches:
      - 1.x

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        php: ['8.0', '8.1', '8.2', '8.3']
        os: [ubuntu-22.04, windows-latest, macos-latest]

    name: PHP ${{ matrix.php }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v3
        with:
          php-version: ${{ matrix.php }}

      - name: Validate composer.json
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php }}-

      - name: Install dependencies
        if: "steps.composer-cache.outputs.cache-hit != 'true'"
        run: composer install --no-progress --no-suggest

      - name: Increase PHP memory limit
        run: echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/memory.ini

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs || true

      - name: Run test suite
        run: vendor/bin/phpunit
